### PR TITLE
Insertions

### PR DESCRIPTION
**Pull request by xadxura**
Updated insertions to use per-glyph per-block size data when available.

### CODE REVIEW

**Comment by behdad** [comment]
Just to make sure. @dscorbett is this something HarfBuzz needs to be updated for?

**Comment by behdad** [comment]
cc @dscrobett

**Comment by behdad** [comment]
cc @dscorbett

**Comment by dscorbett** [comment]
I don’t think this PR requires any update to HarfBuzz. If you mean Egyptian hieroglyphs in general, USE has ambiguous support, and HarfBuzz may require an update depending on the resolutions of MicrosoftDocs/typography-issues#522 and MicrosoftDocs/typography-issues#523.

**Pull request merged**
